import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
test('customer reservation SQL enforces customer ownership, capacity, parent read-only and status timestamps',async()=>{
 const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create schema auth;grant usage on schema auth,public to authenticated,anon;create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant execute on function auth.uid() to authenticated;create table profiles(id uuid primary key,parent_user_id uuid,role text,status text);create table customers(id bigint primary key,owner_user_id uuid);grant select on profiles,customers to authenticated;create table share_boards(id uuid primary key,created_by uuid,company_name text,symbol text,currency text,total_shares numeric,remaining_shares numeric,board_date date,updated_at timestamptz);insert into profiles values('${id(1)}',null,'level1','active'),('${id(2)}','${id(1)}','level2','active'),('${id(3)}','${id(1)}','level2','active');insert into customers values(10,'${id(2)}'),(11,'${id(3)}');`);
 await db.exec(await readFile(new URL('../migrations/20261008_allocation_projects.sql',import.meta.url),'utf8'));const setup=await readFile(new URL('../customer-reservations-setup.sql',import.meta.url),'utf8');await db.exec(setup);await db.exec(setup);
 const as=async(n,sql)=>{await db.exec(`reset role;set role authenticated;select set_config('request.jwt.claim.sub','${id(n)}',false)`);return db.query(sql)};
 const p=(await as(2,`insert into allocation_projects(owner_user_id,project_number,name,total_shares,remaining_shares,customer_ledger_enabled) values('${id(2)}',1,'P',100,100,true) returning id`)).rows[0].id;
 const insert=(n,c,qty,status='confirmed',time="'2026-10-07T12:00:00Z'")=>as(n,`insert into allocation_customer_reservations(project_id,owner_user_id,customer_id,reserved_shares,status,confirmed_at) values('${p}','${id(2)}',${c},${qty},'${status}',${time}) returning id`);
 await insert(2,10,60);await assert.rejects(()=>as(2,`update allocation_projects set total_shares=50,remaining_shares=50 where id='${p}'`));await assert.rejects(()=>as(2,`update allocation_projects set customer_ledger_enabled=false where id='${p}'`));await assert.rejects(()=>insert(2,10,41));await assert.rejects(()=>insert(2,11,1));await assert.rejects(()=>insert(3,10,1));await assert.rejects(()=>insert(1,10,1));await assert.rejects(()=>insert(2,10,1,'confirmed','null'));await insert(2,10,90,'pending','null');
 assert.equal((await as(1,'select * from allocation_customer_reservations')).rows.length,2);assert.equal((await as(3,'select * from allocation_customer_reservations')).rows.length,0);assert.equal((await as(1,"update allocation_customer_reservations set reserved_shares=1 returning id")).rows.length,0);
 await assert.rejects(()=>as(2,`update allocation_customer_reservations set customer_id=11`));await db.exec('reset role;set role anon');await assert.rejects(()=>db.query('select * from allocation_customer_reservations'));
 }finally{await db.close();}
});
